language: cpp
compiler: clang

sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - clang-3.6
    
script: make && make test
